import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerMetadataTools } from "./metadata.js";
import { registerObjectTools } from "./objects.js";
import { registerAutomationTools } from "./automation.js";
import { registerSecurityTools } from "./security.js";
import { registerUiTools } from "./ui.js";
import { registerApexTools } from "./apex.js";
import { registerLwcTools } from "./lwc.js";
import { registerExperienceTools } from "./experience.js";
import { registerAgentforceTools } from "./agentforce.js";
import { registerDeploymentTools } from "./deployment.js";
import { registerMcpTools } from "./mcp.js";
import { registerIntegrationTools } from "./integrations.js";
import { registerReportTools } from "./reports.js";
import { registerDataTools } from "./data.js";
import { registerOmniStudioTools } from "./omnistudio.js";
import { registerOmniChannelTools } from "./omnichannel.js";
import { registerAuditTools } from "./audit.js";
import { registerEinsteinTools } from "./einstein.js";
import { registerAdminTools } from "./admin.js";
import { registerMonitoringTools } from "./monitoring.js";
import { registerCommsTools } from "./comms.js";
import { registerDevOpsTools } from "./devops.js";
import { registerCpqTools } from "./cpq.js";
import { registerVisualforceTools } from "./visualforce.js";
import { registerActionTools } from "./actions.js";
import { registerPageTools } from "./pages.js";
import { registerKnowledgeTools } from "./knowledge.js";
import { registerIdentityTools } from "./identity.js";
import { registerSandboxTools } from "./sandbox.js";
import { registerStreamingTools } from "./streaming.js";
import { registerAuraTools } from "./aura.js";
import { registerFlowManagementTools } from "./flows.js";
import { registerI18nTools } from "./i18n.js";

export function registerTools(server: McpServer): void {
  registerMetadataTools(server);
  registerObjectTools(server);
  registerAutomationTools(server);
  registerSecurityTools(server);
  registerUiTools(server);
  registerApexTools(server);
  registerLwcTools(server);
  registerExperienceTools(server);
  registerAgentforceTools(server);
  registerDeploymentTools(server);
  registerMcpTools(server);
  registerIntegrationTools(server);
  registerReportTools(server);
  registerDataTools(server);
  registerOmniStudioTools(server);
  registerOmniChannelTools(server);
  registerAuditTools(server);
  registerEinsteinTools(server);
  registerAdminTools(server);
  registerMonitoringTools(server);
  registerCommsTools(server);
  registerDevOpsTools(server);
  registerCpqTools(server);
  registerVisualforceTools(server);
  registerActionTools(server);
  registerPageTools(server);
  registerKnowledgeTools(server);
  registerIdentityTools(server);
  registerSandboxTools(server);
  registerStreamingTools(server);
  registerAuraTools(server);
  registerFlowManagementTools(server);
  registerI18nTools(server);
}
